# Generated by Django 3.1.3 on 2020-12-02 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelupapi', '0005_auto_20201201_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', related_query_name='registration', to='levelupapi.event'),
        ),
        migrations.AlterField(
            model_name='gamerevent',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', related_query_name='registration', to='levelupapi.gamer'),
        ),
    ]
